feat: upload files

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -12,44 +12,30 @@ echo "Styling, linting, testing and building your project before committing [Pre
 # Check tsconfig standards
 yarn check-types ||
 (
-    echo '❌❌❌ Failed Type check. ❌❌❌
-            Are you seriously trying to write that? Make the changes required above.'
-    false;
+  echo '❌❌❌ Failed Type check. ❌❌❌
+    Are you seriously trying to write that? Make the changes required above.'
+  false;
 )
 
-yarn check-eslint ||
+yarn check-lint ||
 (
-        echo '🙅‍♀️🙅‍♀️🙅‍♀️ Get that weak shit out of here! 🙅‍♀️🙅‍♀️🙅‍♀️
-                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
-        false; 
-)
-
-# yarn check-eslint:dev ||
-# (
-#         echo '😤🏀👋😤 Get that weak shit out of here! 😤🏀👋😤 
-#                 ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
-#         false; 
-# )
-
-yarn test ||
-(
-    echo '🧪🧪🧪 Report from coverage 🧪🧪🧪'
-    false;
+  echo '🙅‍♀️🙅‍♀️🙅‍♀️ Get that weak shit out of here! 🙅‍♀️🙅‍♀️🙅‍♀️
+    ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
+  false; 
 )
 
 # If everything passes... Now we can commit
 echo '👍👍👍 Your code is passed! I am building. 👍👍👍'
 echo 'Please waiting, take a sip of coffee and relax...'
 
-yarn build:dev ||
+yarn build ||
 (
-    echo '😲😲😲 Oops!! Failed building 😲😲😲
-            Next build failed: View the errors above to see why. 
-    '
-    false;
+  echo '😲😲😲 Oops!! Failed building 😲😲😲
+    Next build failed: View the errors above to see why.'
+  false;
 )
 
 # # If everything passes... Now we can commit
-echo '🚀🚀🚀🚀 You win this time... I am pushed this now. 🚀'
+echo '🚀🚀 You win this time... I am pushed this now. 🚀🚀'
 echo "🎉🎉🎉 FINISH AT : $(date +%d/%m/%Y-%H:%M:%S) 🎉🎉🎉"
 echo "⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼"
